### ISSUE TITLE
Fatal Error when Results Text Graduation is Activated in WP-Adv-Quiz v1.0.3

### ISSUE THREAD

**Issue by amanokatsutoshi** [markusbegerow/wp-adv-quiz#65]
### Description
After updating WP-Adv-Quiz from version 1.0.2 to 1.0.3 on the WordPress dashboard, a fatal error occurs when attempting to display quizzes with results text graduation activated.

### Steps to Reproduce
1. Create a quiz in v1.0.2 with results text graduation activated, and try to display the quiz after updating to v1.0.3.
2. Create a new quiz in v1.0.3 with results text graduation activated.

### Expected Behavior
Quizzes with results text graduation should display without errors after the update.

### Actual Behavior
A fatal error occurs in both scenarios 1, 2 mentioned above.

### Error Log (1)
```
[Tue Jan 23 14:04:43.922259 2024] [php:warn] [pid 724] [client xxx.xxx.xxx.xxx:42436] PHP Warning:  Array to string conversion in /var/www/html/wproot/wp-includes/kses.php on line 1744
[Tue Jan 23 14:04:43.922313 2024] [php:warn] [pid 724] [client xxx.xxx.xxx.xxx:42436] PHP Warning:  Array to string conversion in /var/www/html/wproot/wp-includes/kses.php on line 1744
[Tue Jan 23 14:04:43.922856 2024] [php:error] [pid 724] [client xxx.xxx.xxx.xxx:42436] PHP Fatal error:  Uncaught TypeError: str_contains(): Argument #1 ($haystack) must be of type string, array given in /var/www/html/wproot/wp-includes/blocks.php:1188
Stack trace:
#0 /var/www/html/wproot/wp-includes/blocks.php(1188): str_contains()
#1 /var/www/html/wproot/wp-includes/formatting.php(5226): filter_block_content()
#2 /var/www/html/wproot/wp-includes/class-wp-hook.php(324): wp_pre_kses_block_attributes()
#3 /var/www/html/wproot/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/html/wproot/wp-includes/kses.php(946): apply_filters()
#5 /var/www/html/wproot/wp-includes/kses.php(754): wp_kses_hook()
#6 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/view/WpAdvQuiz_View_FrontQuiz.php(68): wp_kses()
#7 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/controller/WpAdvQuiz_Controller_Front.php(218): WpAdvQuiz_View_FrontQuiz->show()
#8 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/controller/WpAdvQuiz_Controller_Front.php(104): WpAdvQuiz_Controller_Front->handleShortCode()
#9 /var/www/html/wproot/wp-includes/shortcodes.php(433): WpAdvQuiz_Controller_Front->shortcode()
#10 [internal function]: do_shortcode_tag()
#11 /var/www/html/wproot/wp-includes/shortcodes.php(273): preg_replace_callback()
#12 /var/www/html/wproot/wp-includes/class-wp-hook.php(324): do_shortcode()
#13 /var/www/html/wproot/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#14 /var/www/html/wproot/wp-includes/post-template.php(256): apply_filters()
#15 /var/www/html/wproot/wp-content/themes/themename/template-parts/content-single.php(30): the_content()
#16 /var/www/html/wproot/wp-includes/template.php(792): require('...')
#17 /var/www/html/wproot/wp-includes/template.php(725): load_template()
#18 /var/www/html/wproot/wp-includes/general-template.php(206): locate_template()
#19 /var/www/html/wproot/wp-content/themes/themename/single.php(15): get_template_part()
#20 /var/www/html/wproot/wp-includes/template-loader.php(106): include('...')
#21 /var/www/html/wproot/wp-blog-header.php(19): require_once('...')
#22 /var/www/html/wproot/index.php(17): require('...')
#23 {main}
  thrown in /var/www/html/wproot/wp-includes/blocks.php on line 1188
```
### Error Log (2)
```
[Tue Jan 23 14:31:38.718726 2024] [php:warn] [pid 720] [client xxx.xxx.xxx.xxx:36166] PHP Warning:  Array to string conversion in /var/www/html/wproot/wp-includes/kses.php on line 1744, referer: http://localhost/wproot/wp-admin/admin.php?_wpnonce=a10428c429&page=wpAdvQuiz&action=addEdit
[Tue Jan 23 14:31:38.719256 2024] [php:warn] [pid 720] [client xxx.xxx.xxx.xxx:36166] PHP Warning:  Array to string conversion in /var/www/html/wproot/wp-includes/kses.php on line 1744, referer: http://localhost/wproot/wp-admin/admin.php?_wpnonce=a10428c429&page=wpAdvQuiz&action=addEdit
[Tue Jan 23 14:31:38.719351 2024] [php:error] [pid 720] [client xxx.xxx.xxx.xxx:36166] PHP Fatal error:  Uncaught TypeError: str_contains(): Argument #1 ($haystack) must be of type string, array given in /var/www/html/wproot/wp-includes/blocks.php:1188
Stack trace:
#0 /var/www/html/wproot/wp-includes/blocks.php(1188): str_contains()
#1 /var/www/html/wproot/wp-includes/formatting.php(5226): filter_block_content()
#2 /var/www/html/wproot/wp-includes/class-wp-hook.php(324): wp_pre_kses_block_attributes()
#3 /var/www/html/wproot/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/html/wproot/wp-includes/kses.php(946): apply_filters()
#5 /var/www/html/wproot/wp-includes/kses.php(754): wp_kses_hook()
#6 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/view/WpAdvQuiz_View_QuizEdit.php(888): wp_kses()
#7 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/view/WpAdvQuiz_View_QuizEdit.php(183): WpAdvQuiz_View_QuizEdit->postBoxResult()
#8 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/view/WpAdvQuiz_View_QuizEdit.php(136): WpAdvQuiz_View_QuizEdit->tabResult()
#9 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/view/WpAdvQuiz_View_QuizEdit.php(46): WpAdvQuiz_View_QuizEdit->tabContents()
#10 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/controller/WpAdvQuiz_Controller_Quiz.php(196): WpAdvQuiz_View_QuizEdit->show()
#11 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/controller/WpAdvQuiz_Controller_Quiz.php(19): WpAdvQuiz_Controller_Quiz->addEditQuiz()
#12 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/controller/WpAdvQuiz_Controller_Admin.php(231): WpAdvQuiz_Controller_Quiz->route()
#13 /var/www/html/wproot/wp-content/plugins/advanced-quiz/lib/controller/WpAdvQuiz_Controller_Admin.php(163): WpAdvQuiz_Controller_Admin->_route()
#14 /var/www/html/wproot/wp-includes/class-wp-hook.php(324): WpAdvQuiz_Controller_Admin->route()
#15 /var/www/html/wproot/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 /var/www/html/wproot/wp-includes/plugin.php(517): WP_Hook->do_action()
#17 /var/www/html/wproot/wp-admin/admin.php(259): do_action()
#18 {main}
  thrown in /var/www/html/wproot/wp-includes/blocks.php on line 1188, referer: http://localhost/wproot/wp-admin/admin.php?_wpnonce=a10428c429&page=wpAdvQuiz&action=addEdit
```
### Environment
- WordPress Version: 6.4.2
- PHP Version: 8.1

**Comment by markusbegerow** [comment]
Hey @amanokatsutoshi ,

fix is comin'
![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/c6ff37bb-a449-484a-823b-9496fe8447ba)

**Comment by amanokatsutoshi** [comment]
Thank you for addressing the issue. However, I'm facing difficulty in obtaining the fixed version. I've been attempting to update from 1.0.2 again by the following two ways since yesterday:

1. I tried updating to 1.0.3 from the WordPress dashboard again.
2. I attempted to manually update by downloading what seemed to be the latest version from [Releases](https://github.com/markusbegerow/wp-adv-quiz/releases).

Despite these efforts, I haven't been able to access the fixed version. Could you please provide guidance on how we can obtain the fixed release?

Thank you once again for your attention to this matter.

**Comment by amanokatsutoshi** [comment]
I may have misunderstood. Does it mean that the fixed version has not been released yet and will be included in the next release?
If so, I'll wait for the release of the next version. Thank you very much.

**Comment by markusbegerow** [comment]
Update is there
