### ISSUE TITLE
Serious Quiz Errors

### ISSUE THREAD

**Issue by DzhumaID** [markusbegerow/wp-adv-quiz#69]
If we place more than one quiz on a page, everything breaks and none of them work. The console gives us the following error.

VM747748:3 Uncaught TypeError: Cannot read properties of undefined (reading 'catId')
    at eval (eval at <anonymous> (online-english-test/:1:1), <anonymous>:3:3449)
    at Array.sort (<anonymous>)
    at Object.sortCategories (eval at <anonymous> (online-english-test/:1:1), <anonymous>:3:3291)
    at Object.startQuiz (eval at <anonymous> (online-english-test/:1:1), <anonymous>:1:12081)
    at HTMLInputElement.eval (eval at <anonymous> (online-english-test/:1:1), <anonymous>:4:4215)
    at HTMLInputElement.dispatch (jquery.min.js,qver=3.7.1.pagespeed.jm.PoWN7KAtLT.js:1:40035)
    at v.handle (jquery.min.js,qver=3.7.1.pagespeed.jm.PoWN7KAtLT.js:1:38006)
eval @ VM747748:3
sortCategories @ VM747748:3
startQuiz @ VM747748:1
eval @ VM747748:4
dispatch @ jquery.min.js,qver=3.7.1.pagespeed.jm.PoWN7KAtLT.js:1
v.handle @ jquery.min.js,qver=3.7.1.pagespeed.jm.PoWN7KAtLT.js:1

<img width="1510" alt="Снимок экрана 2024-02-13 в 14 54 42" src="https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/6c98e09b-70e7-4ca7-9757-30ed2b9c1b25">

The plugin supports step-by-step passage of several quizzes (to pass quiz 1, you must first pass quiz 2 and only after that quiz 1 will become available) - this model also does not work due to this error!

**Comment by DzhumaID** [comment]
I want to make several different quizzes and place them on one page.
Please tell me how to do this so that this error does not occur? Or is this a bug in the plugin code and you need to wait for the plugin to be updated?
PHP version 8.2 included
plugin updated, version installed 1.0.3

**Comment by markusbegerow** [comment]
Hey @DzhumaID ,

at the moment one quiz is possible, not more.
